spring.application.name=Farm2You
spring.profiles.active = local
springdoc.swagger-ui.display-request-duration = true
spring.web.resources.static-locations=file:///C:/Users/jundr/Desktop/Growthon_BE/resources/images